import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProviders } from "./providers";
import { Flex } from "@chakra-ui/react";
import RightSidebar from "@/components/RightSidebar";
import LeftNavigationSidebar from "@/components/navigation/LeftNavigationSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviders>
          <Flex 
            h='100vh'
            overflow='hidden'
            maxW='100%'
            justify='center'
            backgroundColor='#FAFAFB'
          >
            <LeftNavigationSidebar />
            <Flex minW='830px' grow={1}>
              {children}
            </Flex>
            <RightSidebar />
          </Flex>
        </ChakraProviders>
      </body>
    </html>
  );
}
